const { createClient } = require('@supabase/supabase-js')
const { execSync } = require('child_process')
const fs = require('fs')
const path = require('path')
require('dotenv').config({ path: '.env.local' })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
)

// ── CLIENT CONFIG ─────────────────────────────────────────
// Pass as args: node onboard-client.js "Client Name" rfc clave company_id
// Example: node onboard-client.js "Duratech Industries" DUR001234567 1234 duratech

const CLIENT_NAME  = process.argv[2]
const CLIENT_RFC   = process.argv[3]
const CLIENT_CLAVE = process.argv[4]
const COMPANY_ID   = process.argv[5]

if (!CLIENT_NAME || !CLIENT_RFC || !CLIENT_CLAVE || !COMPANY_ID) {
  console.log('Usage: node scripts/onboard-client.js "Client Name" RFC CLAVE company_id')
  console.log('Example: node scripts/onboard-client.js "Duratech Industries" DUR001234567 1234 duratech')
  process.exit(0)
}

const PORTAL_REPO = path.join(process.env.HOME, 'evco-portal')
const PORTAL_NAME = `${COMPANY_ID}-portal`

function step(n, label) {
  console.log(`\n── STEP ${n}: ${label}`)
}

function ok(msg) { console.log(`  ✅ ${msg}`) }
function warn(msg) { console.log(`  ⚠️  ${msg}`) }
function fail(msg) { console.log(`  ❌ ${msg}`) }

async function onboardClient() {
  console.log(`\n🦀 CRUZ CLIENT ONBOARDING`)
  console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
  console.log(`Client:     ${CLIENT_NAME}`)
  console.log(`RFC:        ${CLIENT_RFC}`)
  console.log(`Clave:      ${CLIENT_CLAVE}`)
  console.log(`Company ID: ${COMPANY_ID}`)
  console.log(`Portal:     ${PORTAL_NAME}.vercel.app`)
  console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)

  // ── STEP 1: Supabase tenant check ─────────────────────
  step(1, 'Supabase data check')

  const { count: trafCount } = await supabase
    .from('traficos').select('*', { count: 'exact', head: true })
    .eq('company_id', COMPANY_ID)

  const { count: entCount } = await supabase
    .from('entradas').select('*', { count: 'exact', head: true })
    .eq('company_id', COMPANY_ID)

  const { count: factCount } = await supabase
    .from('aduanet_facturas').select('*', { count: 'exact', head: true })
    .eq('clave_cliente', CLIENT_CLAVE)

  console.log(`  traficos:         ${(trafCount || 0).toLocaleString()}`)
  console.log(`  entradas:         ${(entCount || 0).toLocaleString()}`)
  console.log(`  aduanet_facturas: ${(factCount || 0).toLocaleString()}`)

  if (trafCount === 0) warn(`No traficos found for company_id="${COMPANY_ID}" — portal will show empty state`)
  else ok(`${trafCount} traficos found`)

  // ── STEP 2: Create client config file ─────────────────
  step(2, 'Creating client config')

  const configContent = `// src/lib/client-config.ts
// Auto-generated by CRUZ onboarding — ${new Date().toISOString()}
// Client: ${CLIENT_NAME}

export const CLIENT_NAME = '${CLIENT_NAME}'
export const CLIENT_RFC = '${CLIENT_RFC}'
export const CLIENT_CLAVE = '${CLIENT_CLAVE}'
export const COMPANY_ID = '${COMPANY_ID}'
export const PORTAL_URL = '${PORTAL_NAME}.vercel.app'
export const PATENTE = '3596'
export const ADUANA = '240'
`

  const portalConfigPath = path.join(PORTAL_REPO, 'src', 'lib', 'client-config.ts')
  const backupPath = portalConfigPath + '.evco.backup'

  // Backup EVCO config
  if (fs.existsSync(portalConfigPath) && !fs.existsSync(backupPath)) {
    fs.copyFileSync(portalConfigPath, backupPath)
    ok(`EVCO config backed up to client-config.ts.evco.backup`)
  }

  fs.writeFileSync(portalConfigPath, configContent)
  ok(`client-config.ts updated for ${CLIENT_NAME}`)

  // ── STEP 3: Build ──────────────────────────────────────
  step(3, 'Building portal')

  try {
    console.log('  Running next build...')
    execSync('npx next build', { cwd: PORTAL_REPO, stdio: 'pipe' })
    ok('Build successful')
  } catch (e) {
    fail('Build failed — check errors above')
    console.log(e.stdout?.toString() || e.message)
    process.exit(1)
  }

  // ── STEP 4: Deploy to Vercel ───────────────────────────
  step(4, `Deploying to Vercel as ${PORTAL_NAME}`)

  try {
    const result = execSync(
      `vercel --prod --yes --name ${PORTAL_NAME}`,
      { cwd: PORTAL_REPO, encoding: 'utf8' }
    )
    const urlMatch = result.match(/https:\/\/[^\s]+vercel\.app/)
    const url = urlMatch ? urlMatch[0] : `https://${PORTAL_NAME}.vercel.app`
    ok(`Deployed: ${url}`)
  } catch (e) {
    warn('Vercel deploy may have encountered an issue — check vercel dashboard')
  }

  // ── STEP 5: Restore EVCO config ────────────────────────
  step(5, 'Restoring EVCO config')

  if (fs.existsSync(backupPath)) {
    fs.copyFileSync(backupPath, portalConfigPath)
    ok('EVCO client-config.ts restored')
  }

  // ── STEP 6: Add crontab entries ────────────────────────
  step(6, 'Adding crontab entries')

  const crontabEntries = `
# ${CLIENT_NAME} — added ${new Date().toLocaleDateString()}
# Uncomment when GlobalPC data is flowing for this client:
# 55 6 * * * cd /Users/$(whoami)/evco-portal && CLIENT_ID=${COMPANY_ID} node scripts/morning-report.js >> /tmp/morning-report-${COMPANY_ID}.log 2>&1
# 0 22 * * 0 cd /Users/$(whoami)/evco-portal && CLIENT_ID=${COMPANY_ID} node scripts/evco-weekly-audit.js >> /tmp/weekly-audit-${COMPANY_ID}.log 2>&1
`

  console.log('  Crontab entries to add when ready:')
  console.log(crontabEntries)

  // ── STEP 7: Generate welcome letter ────────────────────
  step(7, 'Generating welcome letter')

  const today = new Date().toLocaleDateString('es-MX', {
    day: '2-digit', month: 'long', year: 'numeric'
  })

  const letter = `${today}

${CLIENT_NAME}
RFC: ${CLIENT_RFC}

Estimado cliente,

Por medio de la presente, Renato Zapata & Company le da la bienvenida
como cliente de nuestro servicio de agencia aduanal y comercio exterior.

DATOS DE SU OPERACIÓN:
- Clave de cliente: ${CLIENT_CLAVE}
- Patente: 3596
- Aduana: 240 Nuevo Laredo
- Portal de cliente: https://${PORTAL_NAME}.vercel.app

Su portal de cliente le permite consultar en tiempo real:
✓ Estado de sus tráficos e importaciones
✓ Resumen financiero de pedimentos
✓ Entradas de almacén
✓ Reportes semanales de auditoría

Para cualquier consulta, contáctenos en:
ai@renatozapata.com

Atentamente,

Renato Zapata III
Director General
Renato Zapata & Company
Agentes Aduanales · Patente 3596 · Aduana 240 Nuevo Laredo
8402 Killam Industrial Blvd · Laredo, Texas
`

  const letterPath = path.join(process.env.HOME, 'Desktop', `Welcome-${COMPANY_ID.toUpperCase()}.txt`)
  fs.writeFileSync(letterPath, letter)
  ok(`Welcome letter saved: ${letterPath}`)

  // ── SUMMARY ────────────────────────────────────────────
  console.log(`\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
  console.log(`✅ ${CLIENT_NAME} ONBOARDING COMPLETE`)
  console.log(`Portal: https://${PORTAL_NAME}.vercel.app`)
  console.log(`Clave:  ${CLIENT_CLAVE}`)
  console.log(`Welcome letter: ~/Desktop/Welcome-${COMPANY_ID.toUpperCase()}.txt`)
  console.log(`\nNext steps:`)
  console.log(`  1. Send portal URL to client contact`)
  console.log(`  2. Verify GlobalPC has client data flowing`)
  console.log(`  3. Uncomment crontab entries above`)
  console.log(`  4. Run: npm run validate "${CLIENT_NAME}" ${COMPANY_ID} ${CLIENT_CLAVE} https://${PORTAL_NAME}.vercel.app`)
  console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
}

onboardClient().catch(err => {
  console.error('Fatal error:', err)
  process.exit(1)
})
